// ram_w_ctrlsig.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module ram_w_ctrlsig (
		input  wire [10:0] data,      //      data.datain
		output wire [10:0] q,         //         q.dataout
		input  wire [3:0]  wraddress, // wraddress.wraddress
		input  wire [3:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	ram_w_ctrlsig_ram_2port_181_djt6qxq ram_2port_0 (
		.data      (data),      //   input,  width = 11,      data.datain
		.q         (q),         //  output,  width = 11,         q.dataout
		.wraddress (wraddress), //   input,   width = 4, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 4, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
