// weight_rom.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module weight_rom (
		output wire [511:0] q,       //       q.dataout
		input  wire [13:0]  address, // address.address
		input  wire         clock    //   clock.clk
	);

	weight_rom_rom_1port_181_rouiaua rom_1port_0 (
		.q       (q),       //  output,  width = 512,       q.dataout
		.address (address), //   input,   width = 14, address.address
		.clock   (clock)    //   input,    width = 1,   clock.clk
	);

endmodule
