// fp_acc.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module fp_acc (
		input  wire        clk,    //    clk.clk
		input  wire        areset, // areset.reset
		input  wire [31:0] x,      //      x.x
		input  wire        n,      //      n.n
		output wire [31:0] r,      //      r.r
		output wire        xo,     //     xo.xo
		output wire        xu,     //     xu.xu
		output wire        ao,     //     ao.ao
		input  wire [0:0]  en      //     en.en
	);

	fp_acc_altera_fp_acc_custom_181_2tuw37a fp_acc_custom_0 (
		.clk    (clk),    //   input,   width = 1,    clk.clk
		.areset (areset), //   input,   width = 1, areset.reset
		.x      (x),      //   input,  width = 32,      x.x
		.n      (n),      //   input,   width = 1,      n.n
		.r      (r),      //  output,  width = 32,      r.r
		.xo     (xo),     //  output,   width = 1,     xo.xo
		.xu     (xu),     //  output,   width = 1,     xu.xu
		.ao     (ao),     //  output,   width = 1,     ao.ao
		.en     (en)      //   input,   width = 1,     en.en
	);

endmodule
