add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_address
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_read
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/clk
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/reset_n
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_address
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_read
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_write
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/irq
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/clk
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/reset_n
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_stall
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_stall
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_pcb
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/F_vinst
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/D_vinst
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/E_vinst
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/M_vinst
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/A_vinst
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw_avail
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_issue
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_kill
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_kill
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_issue
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_iw
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_iw
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_status_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ienable_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ipending_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_exception_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_exception_reg_cause
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_badaddr_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_badaddr_reg_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cdsr_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cdsr_reg_status
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: F_pc_nxt}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_br_pred_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_br_taken_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_valid_jmp_indirect
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_jmp_direct
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_jmp_direct_target_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_pcb_nxt
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: instruction_master}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_read
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_address
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_readdata_d1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_i_want_inst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_i_hit
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_i_want_read
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_i_read_starting
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_i_consumed
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/i_readdata_d1_valid
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: dynamic_brpred_(frontend)}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_bht_ptr_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_bht_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_iw
add wave -noupdate -format Logic -radix ascii /NIOS2_INSTANCE_TOP/D_vinst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_bht_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_br_cond_pred_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_br_pred_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_br
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_br_uncond
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_br_always_pred_taken
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: dynamic_brpred_(backend)}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_br_cond_pred_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_br_actually_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_br_mispredict
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_br_mispredict
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_br_cond_taken_history
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_wr_data_unfiltered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_wr_data_filtered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_wr_en_unfiltered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_wr_en_filtered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_ptr_unfiltered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_bht_ptr_filtered
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: A_slow_inst_result_mux}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ctrl_ld
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ctrl_ld32
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_result_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_result_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_sel_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_sel
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: exceptions}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_exc_trap_inst_pri15
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_exc_unimp_inst_pri15
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_exc_break_inst_pri15
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_exc_illegal_inst_pri15
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_norm_intr_pri5
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_break_inst_pri15
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ignore_exc
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_any
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_allowed
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_norm_intr_pri5
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_exc_break
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_refetch
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_cancel
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_cancel_except_refetch
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_valid_ignoring_refetch
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_allowed
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_any 
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_break
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_crst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_ext_intr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_any_active
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_break_active
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_active_no_break_no_crst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_active_no_break
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_shadow_active
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_wr_ea_ba
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_debug_mode_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_refetch_required
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_cancel
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: mem}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_mem_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mem_baddr
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: load}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_ld_dcache_management
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_ld8
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_ld16
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_ld_signed
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_inst_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_inst_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_inst_result_aligned
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_data_unfiltered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_data_filtered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ld_align_sh16
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ld_align_sh8
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ld_align_byte1_fill
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ld_align_byte2_byte3_fill
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: store}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_st
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_st8
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_st16
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_st_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_mem_byte_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_st_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mem_byte_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_st_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mem_byte_en
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: register_file}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw_a_rf
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/F_iw_b_rf
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_rf_a
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_rf_b
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_data_unfiltered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wr_data_filtered
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_wr_data
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: alu}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/clk
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_arith_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_arith_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_alu_signed_comparison
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_arith_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_logic_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_compare_op
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_cmp_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_alu_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_cmp
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_logic
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_retaddr
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: hbreak}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/hbreak_req
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/hbreak_enabled
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/wait_for_one_post_bret_inst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_pc
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/oci_async_hbreak_req
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_oci_sync_hbreak_req
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: reg_cmp}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_regnum_a_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_regnum_a_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_regnum_a_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_regnum_a_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_regnum_b_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_regnum_b_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_regnum_b_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_regnum_b_cmp_D
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_a_is_src
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_b_is_src
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_ignore_dst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_ctrl_src2_choose_imm
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_other_rs
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_data_depend
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_dstfield_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_late_result
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_late_result
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: src_operands}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_choose_E
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_choose_M
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_choose_A
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_choose_W
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_choose_E
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_choose_M
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_choose_A
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_choose_W
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_imm
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/D_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_src2
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: shift_rotate}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_en
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_shift_rot
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_shift_rot_right
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_shift_right_arith
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_shift_rot_right
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_rot
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_shift_rot_left
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_n
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_rn
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_fill_bit
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_left_mask
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_mask
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_right_mask
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_prestep1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_prestep2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_step2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_rn
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_fill_bit
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_mask
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_pass0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_pass1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_pass2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_pass3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_sel_fill0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_sel_fill1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_sel_fill2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_rot_sel_fill3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_mask
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_pass0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_pass1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_pass2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_pass3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_sel_fill0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_sel_fill1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_sel_fill2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rot_sel_fill3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_shift_rot_result
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: mul}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_src2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/E_ctrl_mul_lsw
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mul_cell_p1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mul_cell_p2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mul_cell_p3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_mul_s1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mul_cell_p3
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mul_s1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mul_s2
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mul_result
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: data_master}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_address
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_read_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_read
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_readdata_d1
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_write_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_write
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mem_stall_start_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mem_stall_stop_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mem_stall_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_mem_stall
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: A_slow_ld_aligner}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_data_unaligned
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_data_sign_bit
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_data_fill_bit
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld16_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_byte0_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_byte1_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_byte2_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_byte3_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_ld_data_aligned_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_slow_inst_result
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: control_registers}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_ctrl_rd_ctl_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_iw_control_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/M_rdctl_data
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ctrl_wrctl_inst
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_iw_control_regnum
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wrctl_status
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wrctl_estatus
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_wrctl_bstatus
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_ctrl_exception
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_intr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_trap
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_break
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_hbreak
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_eret
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_op_bret
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_eret_src
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_status_reg_pie_inst_nxt
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_status_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ienable_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_ipending_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_exception_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_exception_reg_cause
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_badaddr_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_badaddr_reg_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cdsr_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/W_cdsr_reg_status
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace}
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/cond_dct_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/curr_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/dct_buffer
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/dct_code
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/dct_count
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/dct_is_taken
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/exc_addr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/instr_retired
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/advanced_exc_occured
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_cond_dct
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_dct
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_exception_no_break
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_fast_tlb_miss_exception
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_idct
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/is_uncond_dct
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/itm
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/not_in_debug_mode
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_curr_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_exc_addr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_exc_handler
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_exc_record_handler
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_frametype
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/pending_prev_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/prev_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/prev_pid_valid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/record_dct_outcome_in_sync
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/record_itrace
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/retired_pcb
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/snapped_curr_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/snapped_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/snapped_prev_pid
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/sync_code
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/sync_interval
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/sync_timer_reached_zero
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/sync_timer
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/sync_timer_next
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/trc_clear
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/trc_ctrl
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/trc_ctrl_reg
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci/the_monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa_nios2_oci_itrace/trc_on
add wave -noupdate -divider {monitor_cpu_nios2_altera_nios2_gen2_unit_181_sh4qswa: extra_exc_info}
add wave -noupdate -format Logic -radix decimal /NIOS2_INSTANCE_TOP/A_exc_highest_pri_cause_code
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_highest_pri_baddr
add wave -noupdate -format Logic -radix hexadecimal /NIOS2_INSTANCE_TOP/A_exc_record_baddr

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
