// in_system_source_probe.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module in_system_source_probe (
		output wire [4:0] source,     //    sources.source
		input  wire       source_clk, // source_clk.clk
		input  wire [2:0] probe       //     probes.probe
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (3),
		.source_width            (5),
		.source_initial_value    ("0"),
		.enable_metastability    ("YES")
	) in_system_sources_probes_0 (
		.source     (source),     //  output,  width = 5,    sources.source
		.source_clk (source_clk), //   input,  width = 1, source_clk.clk
		.probe      (probe),      //   input,  width = 3,     probes.probe
		.source_ena (1'b1)        // (terminated),                        
	);

endmodule
