// ram_w.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module ram_w (
		input  wire [511:0] data,      //      data.datain
		output wire [511:0] q,         //         q.dataout
		input  wire [7:0]   wraddress, // wraddress.wraddress
		input  wire [7:0]   rdaddress, // rdaddress.rdaddress
		input  wire         wren,      //      wren.wren
		input  wire         wrclock,   //   wrclock.clk
		input  wire         rdclock    //   rdclock.clk
	);

	ram_w_ram_2port_181_pyapd2a ram_2port_0 (
		.data      (data),      //   input,  width = 512,      data.datain
		.q         (q),         //  output,  width = 512,         q.dataout
		.wraddress (wraddress), //   input,    width = 8, wraddress.wraddress
		.rdaddress (rdaddress), //   input,    width = 8, rdaddress.rdaddress
		.wren      (wren),      //   input,    width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,    width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,    width = 1,   rdclock.clk
	);

endmodule
